# Generated by Django 4.2.7 on 2023-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_first_name_alter_resume_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
