# Generated by Django 4.2.7 on 2023-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_first_name_alter_resume_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
