# Generated by Django 4.2.7 on 2023-12-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_upload_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
