# Generated by Django 4.2.7 on 2023-12-08 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_skills_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='skills_list',
            new_name='skills',
        ),
    ]
