# Generated by Django 4.2.7 on 2023-12-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_location_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='matching_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
