# Generated by Django 4.2.7 on 2023-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_applyjob_matching_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='matching_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
